### Create Comment
POST http://localhost:3000/comment
Content-Type: application/json

{
"postId": "651234567890",
"content": "This is a comment",
"sender": "User2"
}

### Get Comments by Post ID

GET http://localhost:3000/comment/post/651234567890

### Get Comment by ID

GET http://localhost:3000/comment/695ea5a90be47f5376a5f227

### Update Comment
PUT http://localhost:3000/comment/695ea5a90be47f5376a5f227
Content-Type: application/json

{
"content": "Updated comment content"
}

### Delete Comment

DELETE http://localhost:3000/comment/695ea5ae0be47f5376a5f229